
<?php if ($_SESSION['prihlasen'] != false) {?>
<title>Konferenční systém WEB-KONF - Admin panel</title>
</head>
<body> 
  <div class="container-fluid">
    <header>
      <h1 class = "header">KONFERENČNÍ SYSTÉM WEB-KONF </h1> 
      <h3>VZOR SEMESTRÁLNÍ PRÁCE Z PŘEDMĚTU WEB</h3>
      <?php if ($_SESSION['prihlasen'] != false && $this->rank['nazev'] == "HAdmin" || $this->rank['nazev'] == "Admin") {
      ?>                                          
    </header>
    <nav class="navbar navbar-inverse BlueBackground">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a href="index.php">Hlavní stránka</a></li>
          <li><a href="index.php?page=konf">Konference</a></li>
          <li><a href="index.php?page=user"><span class="glyphicon glyphicon-user"></span> <?php echo ($_SESSION['uzivatel']['uzivatel_jmeno']." (".$this->rank['nazev'].")") ?></a></li>
          <?php if ($this->rank['nazev'] == "HAdmin" || $this->rank['nazev'] == "Admin") {?> <li><a href="index.php?page=konf&stav=2">Přijaté příspěvky</a></li><?php }?> 
          <?php if ($this->rank['nazev'] == "HAdmin" || $this->rank['nazev'] == "Admin") {?> <li><a href="index.php?page=konf&stav=3">Nepřijaté příspěvky</a></li><?php }?>          
          <?php if ($this->rank['nazev'] == "Autor") {?> <li><a href="index.php?page=contribution">Nový příspěvek</a></li><?php }?>
          <?php if ($this->rank['nazev'] == "Autor" || $this->rank['nazev'] == "Recenzent") {?><li><a href="index.php?page=public">Publikované příspěvky</li> </a><?php }?>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <?php if ($this->rank['nazev'] == "HAdmin" || $this->rank['nazev'] == "Admin") {?><li><a href="index.php?page=admin"><span class="glyphicon glyphicon-wrench"></span> Admin panel</a></li><?php };?>
        </ul>
        <form method="post"><button type="submit" name="ButtLogout" class="btn navbar-btn navbar-right" style="padding-right: -5px;"> <span class="glyphicon glyphicon-off"> Logout </button></form>
      </div>
    </nav>  
    <h1 class="textTitle">Admin panel</h1>
    <h3 class="textTitle">Úprava informací uživatele</h3>
    <form class="form-horizontal" method="post">
    
    <?php if (isset($_POST['changeInfo']) && $_SESSION['error'] != "") {?> 
      <div class="alert alert-danger"> 
      <?php
        echo $_SESSION['error']."</div>"; 
         }
         else if (isset($_POST['changeInfo']) && $_SESSION['error'] == ""){
          ?>
       <div class="alert alert-success">
       <?php echo $_SESSION['good']."</div>";}?>  
      <div class="form-inline">
        <select class="form-control btn-primary BlueBackground WhiteText" name="userSelect" style="max-width: 15%;"><?php echo $_SESSION['selectBox']['users'] ?></select>
        <button type="submit" name="submitUser" class="btn btn-primary BlueBackground WhiteText">Potvrdit</button>
      </div>
      <br>
          <div class="form-group">
            <label class="control-label col-sm-1" for="uzivatel_jmeno">Uživatelské jméno:</label>
          <div class="col-sm-10">
            <p class="form-control-static"><?php echo $_SESSION['uzivatelChange']['uzivatel_jmeno']?></p>
          </div>
        </div>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
            <input type="password" class="form-control" name="hesloChange" placeholder="Zadejte heslo pro změnu (není třeba)">
          </div>
           <br> 
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
            <input type="text" class="form-control" name="jmenoChange" value="<?php echo $_SESSION['uzivatelChange']['jmeno']?>">
          </div>
           <br>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
            <input type="text" class="form-control" name="emailChange" value="<?php echo $_SESSION['uzivatelChange']['email']?>">
          </div>
           <br>
          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
            <input type="text" class="form-control" name="organizaceChange" value="<?php echo $_SESSION['uzivatelChange']['organizace']?>">
          </div>
           <br>
          <div class="form-group">
            <label class="control-label col-sm-1" for="Hodnost">Hodnost:</label>
          <div class="col-sm-10">
            <select class="form-control btn-primary BlueBackground WhiteText" name="hodnostSelect" style="max-width: 15%;"><?php echo $_SESSION['selectBox']['values'] ?></select>
          </div>
        </div>
         <br> 
        <div class="form-group">
            <label class="control-label col-sm-1" for="Hodnost">Stav:</label>
          <div class="col-sm-10">
            <select class="form-control btn-primary BlueBackground WhiteText" name="stavSelect" style="max-width: 15%;"><?php echo $_SESSION['selectBox']['stav'] ?></select>
          </div>
        </div>
         <br>  
        <div class="inline-group">
          <button type="submit" name="changeInfo" class="btn btn-primary BlueBackground WhiteText">Upravit</button>
        </div>
        <br>
    </form>                                                         
  
    <?php }
  else if ($this->rank['nazev'] != "Admin" || $this->rank['nazev'] != "HAdmin") {
    ?>
                                          
      </header>
      <nav class="navbar navbar-inverse BlueBackground">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a href="index.php">Hlavní stránka</a></li>
          <li><a href="index.php?page=konf">Konference</a></li>
          <li><a href="index.php?page=user"><span class="glyphicon glyphicon-user"></span> <?php echo ($_SESSION['uzivatel']['uzivatel_jmeno']." (".$this->rank['nazev'].")") ?></a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <?php if ($this->rank['nazev'] == "HAdmin" || $this->rank['nazev'] == "Admin") {?><li><a href="index.php?page=admin"><span class="glyphicon glyphicon-wrench"></span> Admin panel</a></li><?php };?>
        </ul>
        <form method="post"><button type="submit" name="ButtLogout" class="btn navbar-btn navbar-right" style="padding-right: -5px;"> <span class="glyphicon glyphicon-off"> Logout </button></form>
      </div>
    </nav>
      <h1 class="textTitle">NEMÁTE OPRÁVNĚNÍ!!</h1>
    
  <?php 
  }
  }
  else { 
  ?>
      <title>Konferenční systém WEB-KONF - Admin panel</title>
</head>
<body> 
  <div class="container-fluid">
    <header>
      <h1 class = "header">KONFERENČNÍ SYSTÉM WEB-KONF </h1> 
      <h3>VZOR SEMESTRÁLNÍ PRÁCE Z PŘEDMĚTU WEB</h3>                                           
    </header>
    <nav class="navbar navbar-inverse BlueBackground">
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><a href="index.php">Hlavní stránka</a></li>
          <li><a href="index.php?page=login">Přihlásit se</a></li>
          <li><a href="index.php?page=acc">Vytvořit nový účet</a></li>
          <li><a href="index.php?page=public">Publikované příspěvky</a></li>
        </ul>
      </div>
    </nav>
  <h1 class="textTitle">NEJSTE PŘIHLÁŠEN, PROSÍM PŘIHLAŠTE SE!!</h1>
  <?php }?>
  