<title><?php echo $this->h_title?></title>
</head>
<body> 
  <div class="container-fluid">
    <header>
      <h1 >WEB konference</h1> 
      <h3>Semestrální práce z předmětu WEB</h3>
    </header>
<nav class="navbar navbar-inverse BlueBackground">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><a href="index.php">Main</a></li>
      <li><a href="index.php?info=temata">Témata</a></li>
      <li><a href="index.php?info=terminy">Termíny</a></li>
      <li><a href="index.php?info=organizatori">Organizátoři</a></li>
      <li><a href="index.php?info=misto">Místo konání</a></li>
      <li><a href="index.php?info=sponzori">Sponzoři</a></li>
      <li><a href="index.php?info=pokyny">Pokyny</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="index.php?page=login"><span class="glyphicon glyphicon-briefcase"></span> WEB konf</a></li>
    </ul>
  </div>
</nav>
             

<article class="article">
  <?php 
  echo $this->b_title;
  echo $this->text; 
  ?>
</article>
      